### PR TITLE
Prevent classes.default from being mutated

### PR DESCRIPTION
**Pull request by rmarscher**
Introduced lodash/cloneDeep to make sure classes.default are not mutated inside mergeClasses().

### CODE REVIEW

**Comment by casesandberg** [comment]
Nice! Can you run `npm run lib` on this and I can then merge it in

**Comment by rmarscher** [comment]
Great! There was no `lib` script in the package.json, but I assume you meant the `gulp js:dist` task. I ran that, added it as the lib script in package.json and rebased the branch. Let me know if you need anything else to get this merged.

**Comment by coopermaruyama** [comment]
Ah, I just made a PR/test to fix this and saw you did it already. Thanks for doing this!

**Comment by casesandberg** [comment]
Perfect!

**Pull request merged**
