### PR TITLE
Modularize lodash and upgrade to lodash 4

### PR DESCRIPTION
**Pull request by jacobrask**
Reduces the file size in this particular project, and also lets projects that depend on reactcss (like react-color, see casesandberg/react-color#182) use the same version of lodash, instead of including both lodash 3 and 4.

### CODE REVIEW

**Comment by casesandberg** [comment]
This is awesome! Can you squash and then I will merge it?

**Comment by jacobrask** [comment]
You want them all as a single commit?

**Comment by paulocmoreno** [comment]
Hi guys, any progress with this issue? If needed I can help. Include the entire lodash is a very big con for reactcss and react-color.

**Comment by casesandberg** [comment]
Thanks for the PR @jacobrask, this is up at `reactcss@1.0.5`

**Pull request merged**
