### PR TITLE
Don't attempt to transform React elements

### LINKED ISSUE #18: Maximum call stack reached trying to pass a React element as a value
will keep attempting to transform the object.

### PR DESCRIPTION
**Pull request by mhahn**
Fixes #18 

--

Not sure what the best way to add a test case for this is.

### CODE REVIEW

**Comment by mhahn** [comment]
hm... it's passing the element through now but the element isn't getting rendered correctly. the on* events don't seem to be firing.

**Comment by mhahn** [comment]
Seems like the not rendering properly is an issue with the component, not how its passed with this.

**Comment by casesandberg** [comment]
If you merge master into this and resolve conflicts I can merge it in!

**Comment by casesandberg** [comment]
Thanks! This has been completely removed in 1.0.0

**Pull request closed without merging**
