### PR TITLE
Fix "styles" to "style"

### PR DESCRIPTION
**Pull request by liady**
Fix the typo and change the DOM attribute "styles" to "style"

### CODE REVIEW

**Comment by casesandberg** [comment]
Thanks @liady !

**Comment by liady** [comment]
[Off topic]
Did you built the documentation framework and components yourself?
Any thoughts on releasing it as an independent project? (It looks very good)

**Comment by casesandberg** [comment]
I did! Thanks @liady!

I am doing one or two more projects with it, and then I will be releasing it as a standalone documentation package!!

**Comment by liady** [comment]
:+1:

**Pull request merged**
